### ISSUE TITLE
can i use this with raspberry pi 3 inbuilt wifi card with nexmon kali 

### ISSUE THREAD

**Issue by PulkitSingh256** [xdavidhu/mitmAP#115]
i have a raspberry pi 3 and i have installed kali nexmon image for monitor mode on rpi3 i was somehow able to create a fake ap with rpi3 default wifi card using fluxion but it was not responding like no one was able to connect to it an etc i have another wifi external card which dows not support ap mode so cant create ap with that but it works well with monitor mode. help me

**Comment by xdavidhu** [comment]
Hey!
Unfortunately you will need a wifi card with AP mode capabilities. I wouldn't recommend using the one built into the pi, since there can be issues with it and an external wifi adapter will always be better.

I'm using the TP-Link TL-WN722N, its a great card and Kali supports it out of the box and it has AP mode and monitor mode as well. Great buy.

**Comment by xdavidhu** [comment]
I’m closing this issue for now because of inactivity.
