### ISSUE TITLE
RPI crash at [I] Configuring AP interface...

### ISSUE THREAD

**Issue by zenety** [xdavidhu/mitmAP#13]
When running "sudo python3 mitmAP_rpi.py" I can complete the steps fine until it wants to start the AP interface. After it's at configuring AP interface I have to physically remove the power from the RPI and reboot it to make it work again.

I can start the ap fine with "sudo /usr/sbin/hostapd /etc/hostapd/hostapd.conf". It shows up on my phone and I can connect.

Is there a way to debug this?
![image](https://cloud.githubusercontent.com/assets/9056070/21076415/e14913e0-bf2a-11e6-8c17-4d40129061fc.png)

Apparently running: "sudo ifconfig "wlan0" up 10.0.0.1 netmask 255.255.255.0" crashes my PI.

**Comment by xdavidhu** [comment]
Interesting, because you don't have a wpa_supplicant pid as well.
On my pi, its working perfectly. Are you using raspbian? Which version? Which pi model?
Also make sure that you entered the correct interface name for the AP.

(Even if you enter something wrongly, or there is issue with the code, your pi should not crash completely, so there is a problem with something else)

**Comment by xdavidhu** [comment]
Closing this issue because of no response from OP.
