### ISSUE TITLE
Is there a way to inject JS?

### ISSUE THREAD

**Issue by hkessel1** [xdavidhu/mitmAP#22]

**Comment by xdavidhu** [comment]
Now it's not possible, but if you just create an AP without any proxy/ssltrip with mitmAP, you could use an other mitm framework on that local 10.0.0.0/24, and use that to inject js.

**Comment by hkessel1** [comment]
Okay, thanks. Glad to see you're still active on here. Do you know any tools specifically that I can use with BeEF?

**Comment by xdavidhu** [comment]
I would suggest [bettercap](https://www.bettercap.org/), but i wasn't able to got it working on the mitmAP's network yet. But maybe it was just a problem on my end. You could try the good old ettercap (great tutorial [here](https://null-byte.wonderhowto.com/how-to/beef-ettercap-pwning-marriage-0156713/)) if everything else fails.

If you want to start a script on startup, just add it (the start command) to your /etc/rc.local file, before the exit line.

**Comment by hkessel1** [comment]
Thanks, but doesn't it require user input? How could I just set the user input to what I want, and then it starts with my preferences on boot, if you know what I mean lol. 
The idea is that when plugged in and booted up it creates an access point that I can ssh into the pi with. Would I have to modify the code? @xdavidhu

**Comment by xdavidhu** [comment]
Oh, i see what you what you want to achive. At this mitmAP does not supports arguments instead of user input. :/
But you still got options.

--------

1. (Thats how i do it, its I guess easier) Create a hotspot on your phone, and connect to it once with the pi. After this the pi will remember, and after this, when u start up the pi, it will connect to your phone. If you have an android, scan the subnet 192.168.43.0/24 with e.g the app named [Fing](https://play.google.com/store/apps/details?id=com.overlook.android.fing&hl=en_GB), and just get the IP of the pi, and connect to it via [JuiceSSH](https://play.google.com/store/apps/details?id=com.sonelli.juicessh&hl=en_GB), or any other ssh client.

2. Run mitmAP to create the config files, and after add this to your /etc/rc.local:
(This should start up the hotspot and the dhcp server on boot. But you will NOT have internet connection when connected to the AP.)
```
dnsmasq
screen -S hostapd -m -d hostapd /etc/hostapd/hostapd.conf
```

**Comment by hkessel1** [comment]
Thanks! However I just left for my trip, I brought my pi with me. Let's say the pi connects to test123 by default, if I name my hotspot test123 will it connect?

**Comment by xdavidhu** [comment]
Hm, I'm not 100% sure, but yes, I suppose it should. Just make sure to set it up with the same encryption/password what the saved AP had.

**Comment by hkessel1** [comment]
Okay, thanks! I love your tool btw.

**Comment by hkessel1** [comment]
Sadly Fing can't scan mobile hotspots :/

**Comment by xdavidhu** [comment]
It can, just press the three dot -> Scan external IP network -> enter '192.168.43.0/24'

**Comment by hkessel1** [comment]
The pi didn't connect. My best bet would be getting to the hotel and then connecting it to hotel wifi via Ethernet. Thanks for the help though.

**Comment by xdavidhu** [comment]
:\ If you will be able to connect to it, be sure to add your hotspot to the saved wifis.

Btw you are welcome! If you have any other questions with this, I'm here to help. :)
