### ISSUE TITLE
Re route all traffic

### ISSUE THREAD

**Issue by Wobble107** [xdavidhu/mitmAP#26]
I've tried to re-route all traffic but it won't work.
Aim to send all user to an Apache server on my pi.

Thanks in advance,
Wo

**Comment by hkessel1** [comment]
I've tried this, it's not as easy as it looks. If you could do it you could only do http.

**Comment by xdavidhu** [comment]
mitmAP can't do that by default, but you could set up an iptables rule to redirect all traffic (if you really want), athough i would not recommend it because than the clients would get all kinds or errors and more importantly no internet.

So I would recommend DNS spoofing rather than redirecting all the trafic if your gole is to redirect all of the clients to your website.
